# Generated by Django 3.1 on 2022-06-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpence',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
