# Generated by Django 3.1 on 2022-06-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20220628_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpence',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
