# Generated by Django 3.1 on 2022-07-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0002_auto_20220704_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.RenameField(
            model_name='addincome',
            old_name='amount',
            new_name='income_amount',
        ),
    ]
