# Generated by Django 3.1 on 2022-07-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0003_auto_20220704_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addincome',
            old_name='description',
            new_name='income_desc',
        ),
        migrations.RenameField(
            model_name='addincome',
            old_name='source',
            new_name='income_source',
        ),
    ]
